"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { CartProvider } from '@/lib/Context';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'theoyoth clothing',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={inter.className}>
        <title>theoyoth clothing</title>
        <CartProvider>
          <Toaster />
          <Navbar />
            {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  )
}
